### ISSUE TITLE
Failed to open a session for the virtual machine: Since v1.13

### ISSUE THREAD

**Issue by lantern6** [aforensics/HiddenVM#15] opened 2021-04-24 01:45 UTC
Hi everyone,

After upgrading to Tails 4.18 and HiddenVM 1.13, I can no longer launch any of my Virtual Machines. I receive the below error.

![Screenshot from 2021-04-24 01-30-56](https://user-images.githubusercontent.com/83102291/115943135-bcd79d80-a49d-11eb-94f9-6485f9435e8f.png)

Result Code: NS_ERROR_FAILURE (0x80004005)

I am yet to do a completely fresh HiddenVM install to see if that will resolve the issue. I just wanted to raise this first so others can see the progression of resolving this.

HiddenVM is a fantastic tool for where I live. Thanks for all the hard work!

**Comment by lantern6** [comment] 2021-04-24 02:13
Unfortunately a fresh install did not resolve the issue. I now have no access to my VMs :(

**Comment by ufxgmtwk** [comment] 2021-04-24 07:23
I'm having the exact same problem. I tried changing seveal of the VM options but the error message was always the same as lantern6's. I only got a different one when disabling virtualization on BIOS. Deleted the VirtualBox files and HiddenVM cache so that HiddenVM would download it from scratch again then re-added the disks and the VMs but the problem persists.

Tails 4.18
HiddenVM 1.13
VirtualBox-6.1_6.1.20-143896~Debian~buster_amd64

**Comment by ufxgmtwk** [comment] 2021-04-24 07:58
A workaround by the HiddenVM team has just been pointed out to me (it's available from both README.rst and https://github.com/aforensics/HiddenVM ):

"Emergency fix for Whonix users if you receive an error preventing VM from booting since VirtualBox 6.1.20 update on 2021-04-20: In each affected VM (Settings > Storage) change 'Type' to e.g. 'AHCI'. VM will then boot as normal. No idea on the security implications of choosing a different controller type from default SAS choice by Whonix project. Ongoing situation. We prefer you by default to have the latest VirtualBox vs. the most recent version Whonix advises for their OVA. Whonix on Tails is by no means the only use case of HiddenVM, and OSes observed to be unaffected in VirtualBox 6.1.20 include Windows, macOS and Ubuntu."

The workaround has worked on my system but I'd recommend not to close this issue yet as others might do as I did and only check here on the off-chance that the team might not yet be aware of the problem. If I hadn't been told about the workaround I probably wouldn't have found it so quickly.

**Comment by lantern6** [comment] 2021-04-24 09:48
Thank you ufxgmtwk! Feel silly for not noticing it there on the front page. I'll be sure to check out README.rst for updates in future!

**Comment by aforensics** [comment] 2021-06-01 13:50
Temporary issue caused by bug in VirtualBox, now resolved by VirtualBox team since 6.1.22. Closed.

**Closed by aforensics** 2021-06-01 13:50 UTC
