### ISSUE TITLE
No audio in HiddenVM>Whonix workstation

### ISSUE THREAD

**Issue by notafanof2020** [aforensics/HiddenVM#9] opened 2020-07-31 15:21 UTC
Hi,

I currently have an issue with audio playing inside my Whonix workstation. To test that this was not a Whonix only issue, I tried several other Linux distros and was unable to get sound working on any. It seems to me that the problem isn't in the virtual machine itself but
- in the communication process between HiddenVM VirtualBox and Whonix
or
- in the communication process between HiddenVM VirtualBox and Tails.

All Host Audio Driver/Audio Controller combinations in Virtual Box have been tested and unfortunately none were able to get sound working. I'm unsure how else I can troubleshoot this and a couple of friends reported the same issue. Is someone able to please help?

Thanks for all the great work on HiddenVM!!! :)

![Screenshot 2](https://user-images.githubusercontent.com/68731305/89049667-1f51a200-d341-11ea-98e0-0ff4818b1ebd.png)

![Screenshot 1](https://user-images.githubusercontent.com/68731305/89049643-18c32a80-d341-11ea-9e24-0a9a7ea623ed.png)

**Comment by aforensics** [comment] 2020-07-31 19:46
At first this didn't look like a hiddenvm issue, but in fact it is. Thank you for reporting.

This seems related to user permissions. With HiddenVM, virtualbox must be executed by the 'clearnet' user, which has very limited system access. I've confirmed that audio currently cannot work. This is definitely something that should be investigated and hopefully solved one day.

**Comment by aforensics** [comment] 2020-07-31 23:01
I think I have a solution. Turns out we need to run a pulseaudio daemon for 'clearnet' and also add that user to the 'audio' group. I will push a change and release a build in the next day or 2. Stay tuned.

**Comment by notafanof2020** [comment] 2020-08-01 03:46
Thanks for the quick investigation! Your fix makes perfect sense.

Happy to help with any testing now or in future!

**Comment by aforensics** [comment] 2020-08-01 20:17
Fixed in v1.4.1

**Closed by aforensics** 2020-08-01 20:17 UTC
